#!/usr/bin/env node
'use strict';

import npm_audit from './npm-audit';

import process from 'node:process';

function main() {
    npm_audit();
}

if (import.meta.url === `file://${process.argv[1]}`) { main(); }
