#!/usr/bin/env node
'use strict';

import child_process from 'node:child_process';
import process from 'node:process';

export default function npm_audit() {
    child_process.execSync('npm audit', { stdio: 'inherit' });
}

function main() {
    npm_audit();
}

if (import.meta.url === `file://${process.argv[1]}`) { main(); }
