#!/usr/bin/env node
'use strict';

import child_process from 'node:child_process';
import process from 'node:process';

export default function snyk() {
    child_process.execSync('npx --yes snyk test --all-projects', { stdio: 'inherit' });
}

function main() {
    snyk();
}

if (import.meta.url === `file://${process.argv[1]}`) { main(); }
