#!/usr/bin/env node
'use strict';

import child_process from 'node:child_process';
import process from 'node:process';

export default function test() {
    child_process.execSync('periscope -v', { stdio: 'inherit' });
}

function main() {
    test();
}

if (import.meta.url === `file://${process.argv[1]}`) { main(); }
