#!/usr/bin/env node
'use strict';

import child_process from 'node:child_process';
import process from 'node:process';

export default function upload() {
    child_process.execSync('npm publish --access=public', { stdio: 'inherit' });
}

function main() {
    upload();
}

if (import.meta.url === `file://${process.argv[1]}`) { main(); }
