---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
jobs:
  Test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
    - uses: "actions/checkout@v4"
    - run: "npm install -g"
    - run: "npm test"
      env:
        SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
