---
name: "Test-Futureproof-OS"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  # POSIX cron format
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html
  schedule:
  # Once every 5 minutes
  # - cron: "*/5 * * * *"
  # Once a day
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  Test-Futureproof-OS:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-node@v4"
      with:
        node-version: "20.17.0"
    - run: |
        npm install -g
        npm test
