---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  Test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-node@v4"
      with:
        node-version: "20.17.0"
    - name: "provision dev tools"
      run: "npm install -g"
    - run: "npm test"
